(FEAT) Navbar の作成
cr3atorsstudio/season-1 pull request #9
Opened 2022-09-11 10:40 UTC by eiko0705

Navbarを作成しました。
<img width="1412" alt="Screen Shot 2022-09-11 at 19 38 53" src="https://user-images.githubusercontent.com/83794734/189523116-496a945c-84fa-4c27-8120-3e7c814e57cb.png">

2022-09-13 00:04 UTC, pluto0004 requested changes
ありがとうございます！！！　全体的にめっちゃいい感じです！
ちょっと気になったのが、nav barの文言が微妙に真ん中じゃないところでした！

色々ガチャガチャやってみましたが、文言全体を覆っている container を取り除いてみたり、
文言自体に固定のwidthをつけたり、したら割と真ん中にすることができたので参考にしてみてください！

<img width="1920" alt="Screen Shot 2022-09-13 at 9 02 27" src="https://user-images.githubusercontent.com/71237103/189779213-d24e9c3c-4e11-49c8-a8a2-cfadf1cd2a27.png">

```
export const Navbar = () => {
  return (
    <div>
      <nav className='px-2 py-8 sm:px-4'>
        <div className='flex flex-wrap items-center justify-between px-2'>
          <a className='flex w-56 items-center' href=''>
            <img
              src='public/images/creatorsstudio.jpeg'
              alt='Creators Studio Logo'
              className='ml-10 mr-5 h-full rounded-lg object-contain sm:h-11'
            />
            <span className='self-center whitespace-nowrap text-xl text-white'>
              Creators Studio
            </span>
          </a>
          <div>
            <ul className='ml-auto flex list-none flex-col lg:flex-row'>
              <li>
                <a className='flex w-40 items-center px-9 py-2 text-white hover:opacity-75'>
                  説明
                </a>
              </li>
              <li>
                <a className='flex w-40 items-center px-9 py-2 text-white hover:opacity-75'>
                  参加する
                </a>
              </li>
            </ul>
          </div>
          <div className='w-56'>
            <button className=' rounded-full border border-pink-400 bg-transparent py-2 px-4  text-white'>
              ウォレット接続
            </button>
          </div>
        </div>
      </nav>
    </div>
  );
};

```

2022-09-13 15:54 UTC, eiko0705 commented
>

2022-09-13 15:56 UTC, eiko0705 commented
レビューありがとうございます！！
中央から結構ズレていますね、気づきませんでした。。。
いただいたもので修正しましたので、改めて確認お願いします！

2022-09-14 00:36 UTC, pluto0004 approved these changes
![LGTM](https://image.lgtmoon.dev/3794)

2022-09-14 00:36 UTC, merged